### ISSUE TITLE
pipeline for lncRNA identification with mRNN

### ISSUE THREAD

**Issue by lanyuchunmo** [hendrixlab/mRNN#6]
Hi, I installed the mRNN, and plan to analysis my datasets  by using mRNN, but I can't found a guide pipeline, and there are sevel python script, how should I start the analysis? I'm planning to start with "mRNN.py" script , but I have no idea about the "--weights" option.

**Comment by lanyuchunmo** [comment]
/path_to_mRNN_install_dir/weights/w10u5.pkl
Traceback (most recent call last):
File "/path_to_mRNN_install_dir/mRNN.py", line 129, in 
main()
File "/path_to_mRNN_install_dir/mRNN.py", line 120, in main
mRNN = model.build_model(parameters['weights'],parameters['embedding_size'],parameters['recurrent_gate_size'],5,parameters['dropout'])
File "/path_to_mRNN_install_dir/model.py", line 216, in build_model
model = load(weights)
File "/path_to_mRNN_install_dir/model.py", line 20, in load
model['config']['layers'] = [getattr(layers, layer['layer'])(**layer['config']) for layer in model['config']['layers']]
TypeError: init() got an unexpected keyword argument 'direction'

How can I fix this error?， my sctript is :
python /path_to_mRNN_install_dir/mRNN.py --output ./mRNN_test.out --weights /path_to_mRNN_install_dir/weights/w10u5.pkl all_RNA_novel_merged_head4000.fasta
